### PR TITLE
Save function slow on VMs with remote disks #243

### PR DESCRIPTION
**Pull request by Johan511**
- [x] Does this PR have a descriptive title that could go in our release notes?
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [x] Should this result in any changes to our documentation, either updating existing docs or adding new ones?
 
#### Reference Issues/PRs
#243

#### What does this implement/fix? Briefly explain your changes.
added protected parameter _coalasce_writes which will coalesce writes if set to true
save() calls is_small write which decides if write should is too small (will be coalesced next time when write is called)

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@johan511, thanks for the PR. Did you time your changes on remote disks?

**Comment by Johan511** [comment]
I haven't run any performance tests, any guidance on how I can test them for remote disks?

**Comment by harsha-simhadri** [comment]
@johan511 try any Azure VM (expect L-series). You might probably be able to rent for a few hours for free.

**Comment by Johan511** [comment]
I haven't found any performance regression tests, do I need to benchmark for both the versions? Is there a data set I can work with?

**Comment by harsha-simhadri** [comment]
@darvg Could you please test this PR on Azure VMs to see if load times have improved?

**Comment by darvg** [comment]
@Johan511, thanks for the PR!

I'm seeing a couple of issues:

1. This error is popping up when I try to compile your fork.
```
/home/t-gollapudis/DiskANN-j/src/index.cpp:266:13: error: no declaration matches ‘bool diskann::Index<T, TagT, LabelT>::is_small_segment()’
 inline bool Index<T, TagT, LabelT>::is_small_segment()
             ^~~~~~~~~~~~~~~~~~~~~~
```

2. Looking through your changes, there seems to be a return out of `save` for small writes, before any IO happens. When does the writing actually happen?

**Comment by darvg** [comment]
@Johan511, I'm still not entirely sure what your code is doing, so I'll be closing the PR for now. Feel free to reopen whenever you get a chance to explain.

**Pull request closed without merging**
