### PR TITLE
Fix condition on ubuntu version in README

### PR DESCRIPTION
**Pull request by harsha-simhadri**
- [ ] Does this PR have a descriptive title that could go in our release notes?
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [ ] Should this result in any changes to our documentation, either updating existing docs or adding new ones?

### CODE REVIEW

**Review by dkaczynski — COMMENTED** [review]
Note that I receive this warning when installing MKL on Ubuntu 22.04 (WSL2):

> This machine uses operating system "Ubuntu Linux version 22.04". Compatibility issues may occur.
Installation can continue; however, product functionality may not meet expectations because this product is untested on this operating system. Suggestion: Check the Release Notes for a list of supported operating systems and install this product on a compliant system.

**Comment by harsha-simhadri** [comment]
> Note that I receive this warning when installing MKL on Ubuntu 22.04 (WSL2):
> 
> > This machine uses operating system "Ubuntu Linux version 22.04". Compatibility issues may occur.
> > Installation can continue; however, product functionality may not meet expectations because this product is untested on this operating system. Suggestion: Check the Release Notes for a list of supported operating systems and install this product on a compliant system.


I see that there are MKL packages for ubuntu 22: https://packages.ubuntu.com/search?keywords=intel-mkl
Does this warning persist despite updating "apt update" to packge info?

**Comment by dkaczynski** [comment]
> > Note that I receive this warning when installing MKL on Ubuntu 22.04 (WSL2):
> > > This machine uses operating system "Ubuntu Linux version 22.04". Compatibility issues may occur.
> > > Installation can continue; however, product functionality may not meet expectations because this product is untested on this operating system. Suggestion: Check the Release Notes for a list of supported operating systems and install this product on a compliant system.
> 
> I see that there are MKL packages for ubuntu 22: https://packages.ubuntu.com/search?keywords=intel-mkl Does this warning persist despite updating "apt update" to packge info?

The warning persisted, but according to Intel's MKL docs, it looks like Ubuntu 22.04 has been added as an officially supported release: https://www.intel.com/content/www/us/en/developer/articles/system-requirements/oneapi-math-kernel-library-system-requirements.html

Based on the version numbering for the intel-mkl library  (`2020.4.304-2ubuntu3`), I'm guessing it's still the 20.04 version, but since it's listed as supported in their official docs, I'm also guessing that they've validated it on 22.04 but simply haven't released a newer version yet.

**Review by dkaczynski — CHANGES_REQUESTED** [review]
`Ubuntu 20.04 or 22.04` (as per Intel's officially supported releases)

**Pull request merged**
