### PR TITLE
Address race condition in `iterate_to_fixed_point`

### PR DESCRIPTION
**Pull request by darvg**
- [ ] Does this PR have a descriptive title that could go in our release notes?
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [ ] Should this result in any changes to our documentation, either updating existing docs or adding new ones?
 
#### What does this implement/fix? Briefly explain your changes.
Adds a lock to avoid a race condition on accesses to `_graph_store`.

#### Any other comments?
Causes minimal increase to static build times (CPU is an AMD EPYC 7763 with 64 cores and 512 GB of RAM): 
- for the 192-dimensional 10M point YFCC dataset from the 2023 [BigANN](https://big-ann-benchmarks.com/neurips23.html) challenge, the build time changes from 2044 seconds to 2062 seconds.
- for a smaller 1M point slice of the above dataset, build times are essentially the same, at around 21 seconds.

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
Could you measure build speed on 40+ core machine?

**Comment by darvg** [comment]
> Could you measure build speed on 40+ core machine?

The AMD EPYC is a 64 core CPU, is that good enough? I've updated the comment above correcting the number of cores.

**Review by rakri — APPROVED** [review]

**Comment by harsha-simhadri** [comment]
Could you please post the build times with 8, 16, 32, 64 threads with R100 and L150 on a 100M dataset (e.g., msspacev-100M)

**Comment by darvg** [comment]
Performance differences are listed below:

|     | 8  cores   | 16 cores    | 32  cores   | 64 cores   |
|-----|-------|-------|-------|------|
| old | 30401 | 20483 | 10727 | 8755 |
| new | 28585 | 16123 | 10898 | 8038 |

**Comment by rakri** [comment]
> Performance differences are listed below for msspacev-100M on moonshine:
> 
> 8 cores	16 cores	32 cores	64 cores
> old	30401	20483	10727	8755
> new	28585	16123	10898	8038

We should also get Gopal's help to check Windows performance as the locking structure is different.

**Comment by darvg** [comment]
Here are the corrected numbers:
|     | 8     | 16    | 32   | 64   | 256  |
|-----|-------|-------|------|------|------|
| old | 23354 | 11993 | 6628 | 3834 | 4700 |
| new | 23487 | 12102 | 6710 | 3988 | 4773 |

Here is the time taken to build on parlayANN with 256 threads:  2192.3s

**Comment by harsha-simhadri** [comment]
> Here are the corrected numbers:
> 
> 8	16	32	64	256
> old	23354	11993	6628	3834	4700
> new	23487	12102	6710	3988	4773
> Here is the time taken to build on parlayANN with 256 threads: 2192.3s

Which machine, R=?, L=?.
and how long does parlayANN takes for 32/64 threads.

**Comment by darvg** [comment]
> > Here are the corrected numbers:
> > 8	16	32	64	256
> > old	23354	11993	6628	3834	4700
> > new	23487	12102	6710	3988	4773
> > Here is the time taken to build on parlayANN with 256 threads: 2192.3s
> 
> Which machine, R=?, L=?. and how long does parlayANN takes for 32/64 threads.

CPU is AMD EPYC 7763 with 256 threads
R = 100, L = 150 as requested
ParlayANN with `PARLAY_NUM_THREADS=32`: 3896s
ParlayANN with `PARLAY_NUM_THREADS=64`: 2809s

**Comment by harsha-simhadri** [comment]
@darvg. Thanks for the info. Let us time this on an intel CPU too before merging

**Comment by darvg** [comment]
Here are the numbers on an intel CPU (moonshine):

|     | 8     | 16    | 32    | 64 |
|-----|-------|-------|-------|------|
| old | 26698 | 14711 | 8867  | 7529 |
| new | 27479 | 19310 | 10290 | 7106 |

These numbers still seem to be all over the place, not sure what to make of them.

**Comment by ryriddle** [comment]
Hi @darvg, could you share steps to reproduce the race condition? I want to fix the Rust implementation if it has this issue.

**Comment by darvg** [comment]
Hi @ryriddle, I'm actually not able to reproduce the race condition on Linux, but it did appear in a CI test for my macOS PR (#474). For reference, you can find my macOS changes [here](https://github.com/darvg/DiskANN/tree/sid/apple), and the CI test that fails [here](https://github.com/microsoft/DiskANN/actions/runs/6517861110/job/17704220738?pr=474).

**Comment by darvg** [comment]
@harsha-simhadri here are updated numbers for an Intel CPU that look much cleaner.
The machine used an Intel(R) Xeon(R) Platinum 8380 CPU with 160 total threads and 500 GB of RAM.

|     | 8     | 16    | 32    | 64 | 160 |
|-----|-------|-------|-------|------|------|
| old | 26422 | 13443 | 7010  | 3749 | 2439 |
| new | 26517 | 13475 | 7013 | 3755 | 2475 |

**Comment by harsha-simhadri** [comment]
> @harsha-simhadri here are updated numbers for an Intel CPU that look much cleaner. The machine used an Intel(R) Xeon(R) Platinum 8380 CPU with 160 total threads and 500 GB of RAM.
> 
> 8	16	32	64	160
> old	26422	13443	7010	3749	2439
> new	26517	13475	7013	3755	2475

Thanks for these numbers. IS this single or dual chip?

**Comment by darvg** [comment]
@harsha-simhadri It's a single chip server, as far as I can tell. The exact spec for the CPU can be found [here](https://www.intel.com/content/www/us/en/products/sku/212287/intel-xeon-platinum-8380-processor-60m-cache-2-30-ghz/specifications.html). The webpage for the server can be found [here](https://www.dell.com/en-us/shop/dell-poweredge-servers/poweredge-r750-rack-server/spd/poweredge-r750/pe_r750_tm_vi_vp_sb).

**Pull request merged**
