### PR TITLE
Support data files loading in separated paths

### PR DESCRIPTION
**Pull request by Sanhaoji2**
This change is adding a new load() function to allow customer to input index_file, pivots_file and compressed_file from different paths. 
Since the SSD write & delete operation impact the read performance significantly, to limit the regression during data refresh, the server may only copy the necessary file to SSD drive, that make the index file place in different path from other data files in this scenario.

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@Sanhaoji2  Could you please add a bit more descriptive text on what scenario or use case this is helping? Thanks!

**Review by harsha-simhadri — CHANGES_REQUESTED** [review]
Please also seperate changes for the new load function from the vc16 compiler error fixes you mentioned and raise seperate PRs. Thanks!

**Comment by Sanhaoji2** [comment]
> @Sanhaoji2 Could you please add a bit more descriptive text on what scenario or use case this is helping? Thanks!

Added description for the processing logic of our server.

**Comment by Sanhaoji2** [comment]
> 

OK

> Please also seperate changes for the new load function from the vc16 compiler error fixes you mentioned and raise seperate PRs. Thanks!

OK.

**Review by harsha-simhadri — APPROVED** [review]

**Pull request merged**
