### PR TITLE
The python bindings were expecting a get_metric() method to exist.

### PR DESCRIPTION
**Pull request by daxpryce**

### CODE REVIEW

**Comment by daxpryce** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by daxpryce** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by daxpryce** [comment]
@microsoft-github-policy-service agree company=Microsoft

**Comment by harsha-simhadri** [comment]
@daxpryce Is this PR still relevant or can we close it?

**Pull request closed without merging**
